### ISSUE TITLE
The provided mode is demaged!

### ISSUE THREAD

**Issue by HuachunWang** [FilippoAleotti/Reversing#12]
I try to downloaded the pretrained model, like psm.tar. It is demaged! 
And I downloaded other pretrained models, only mcn-bm-w-arc.zip is complete!
I tried on chrome, edge and firefox and only zip type is work.
So can you upload other models with zip type?
Thanks!

**Comment by FilippoAleotti** [comment]
Hi,

Are you trying to unzip them? If so, try to load them in PyTorch as they are

**Comment by HuachunWang** [comment]
Hi,
It works! Thank you.
