### ISSUE TITLE
incomplete kitti_2015_train.txt

### ISSUE THREAD

**Issue by MrZilinXiao** [FilippoAleotti/Reversing#13]
Hi! Thank you for your impressive work! But did you notice that `kitti_2015_train.txt` is corrupted located in `mono/utils/filenames/kitti_2015_train.txt`? Paper tells there should be `29K rectiﬁed stereo images` rather than 19K lines in this file.

**Comment by FilippoAleotti** [comment]
Hi,

Thank you, I didn't notice it! I should have fixed it now

**Comment by MrZilinXiao** [comment]
Great! Thank you for your quick solution!

**Comment by MrZilinXiao** [comment]
Sorry again... I was wondering the way you exclude KITTI 2015 scene from KITTI Raw. I didn't find any clues... Did you have a filelist that indicates which part of KITTI Raw belongs to KITTI 2015?

**Comment by MrZilinXiao** [comment]
pop it up in case you didn't notice that I reopened the issue...

**Comment by FilippoAleotti** [comment]
Hi, 
we used the KITTI train split available here: https://github.com/mrharicot/monodepth/tree/master/utils/filenames
However, in KITTI should exist a mapping file to filter out such images

**Comment by MrZilinXiao** [comment]
> Hi,
> we used the KITTI train split available here: https://github.com/mrharicot/monodepth/tree/master/utils/filenames
> However, in KITTI should exist a mapping file to filter out such images

Understood. Thank you for your time.
