### ISSUE TITLE
Question about results in Table1 and Table3

### ISSUE THREAD

**Issue by LukeCho-8810** [FilippoAleotti/Reversing#5]
Hi,
Thanks for your great work.
I have a question about the settings of experiments in Table 1 and Table 3.
In Table 1, it said that results were tested on KITTI 2015 training set. And in Table 3, it was said that results were tested on KITTI 2015. So, were the results of Table 3 also tested on training set or on the whole dataset(200 images)?

And In Table 3, best result of D1 is 2.78, with 92.53% density. In Table 1, best result of D1 is 3.68, with 100% density. Does it mean that MCN already can get good enough results?

Thanks

**Comment by FilippoAleotti** [comment]
Hi,

About your first question yes, we test both on KITTI 2015 training split (with 200 ground truth images). About MCN, it proved to be quite accurate if compared to a "plain" monocular network, but if we compare it with a stereo model the latter is more accurate if evaluated densely.
