### ISSUE TITLE
Better results without accounting for difficult images in Middlebury

### ISSUE THREAD

**Issue by serizba** [FilippoAleotti/Reversing#9]
Hi,

Thanks for publishing this great work.

I was testing your code on Middlebury and I realized that you obtain slightly better results when you don't multiply by 0.5 on difficult images. 
Are you applying this factor because some other previous work did the same or there is any other reason to do it? If there is a previous work that does this scaling, could you tell me which?

By the way, I am referring to this:
```python
difficult_images = ["PianoL", "Playroom", "Playtable", "Shelves", "Vintage"]
...
...
if seq in difficult_images:
    scalar = 0.5
```

Thanks in advance,
Sergio

**Comment by FilippoAleotti** [comment]
Hi,

We used the weights reported in the benchmark (the green bars) of training sparse set:

https://vision.middlebury.edu/stereo/eval3/

**Comment by serizba** [comment]
Hi,

Oh, thanks, I didn't know about this.

Thanks!

**Comment by ksh11023** [comment]
@serizba

Hello,
Have you reproduced this repo with the pretrained model ?
